"""Adversarial Motion Prior (AMP) On-Policy Runner for roller-skating.

This runner extends the standard RSL-RL OnPolicyRunner with an AMP
discriminator that provides style rewards from reference skating motions.

Architecture (based on Peng et al., SIGGRAPH 2021 and HUSKY, arXiv:2602.03205):
  - Discriminator D: MLP(amp_obs_dim → 1), sigmoid output
  - Expert buffer: fixed reference motion transitions sampled from NPZ
  - Policy buffer: rolling window of policy rollout AMP observations
  - AMP reward: r_AMP = -log(1 - D(s_policy))
  - Discriminator loss: BCE(D(s_expert)=1) + BCE(D(s_policy)=0) + gradient penalty

The style reward is blended with the task reward:
    r_total = (1 - amp_lerp) * r_task + amp_lerp * r_AMP

AMP observations are expected in `infos["amp_obs"]` from the environment
(shape: num_envs × amp_obs_dim). These are set in the env by adding an
AMP observation group or extracted from the extras dict.
"""

from __future__ import annotations

import os
import time
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import deque
from typing import TYPE_CHECKING

from rsl_rl.runners import OnPolicyRunner

if TYPE_CHECKING:
    from rsl_rl.env import VecEnv


class AmpDiscriminator(nn.Module):
    """Lightweight discriminator MLP for AMP style reward.

    Args:
        amp_obs_dim:  Dimension of the AMP observation state.
        hidden_dims:  Hidden layer sizes.
        activation:   Activation function name.
    """

    def __init__(
        self,
        amp_obs_dim: int,
        hidden_dims: list[int] = (1024, 512),
        activation: str = "leaky_relu",
    ):
        super().__init__()
        act_fn = {
            "relu": nn.ReLU,
            "leaky_relu": nn.LeakyReLU,
            "elu": nn.ELU,
            "tanh": nn.Tanh,
        }[activation]

        # Spectral normalisation enforces the Lipschitz constraint on the
        # discriminator without requiring create_graph=True autograd calls,
        # which conflict with Isaac Sim / PhysX CUDA streams.
        layers: list[nn.Module] = []
        in_dim = amp_obs_dim
        for h in hidden_dims:
            layers += [nn.utils.spectral_norm(nn.Linear(in_dim, h)), act_fn()]
            in_dim = h
        layers.append(nn.utils.spectral_norm(nn.Linear(in_dim, 1)))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)

    def get_reward(self, amp_obs: torch.Tensor) -> torch.Tensor:
        """Compute AMP reward: -log(1 - sigmoid(D(s))), clipped to [0, 2]."""
        with torch.no_grad():
            logits = self.forward(amp_obs)
            prob = torch.sigmoid(logits).squeeze(-1)
            # Numerically stable AMP reward = max(0, -log(1 - p))
            reward = -torch.log(torch.clamp(1.0 - prob, min=1e-6))
        return reward.clamp(0.0, 2.0)


class ExpertMotionBuffer:
    """Circular buffer holding AMP observations from expert reference motion.

    Samples random transitions from the pre-loaded reference NPZ file.

    Args:
        motion_npz_path:  Path to the reference motion NPZ file.
        amp_obs_dim:      Expected AMP obs dimension.
        device:           PyTorch device string.
        buffer_size:      How many expert transitions to cache in GPU memory.
    """

    def __init__(
        self,
        motion_npz_path: str,
        amp_obs_dim: int,
        device: str = "cpu",
        buffer_size: int = 100_000,
    ):
        self.device = device
        self.amp_obs_dim = amp_obs_dim

        if not os.path.isfile(motion_npz_path):
            print(
                f"[AmpRunner] WARNING: reference motion file not found at:\n  {motion_npz_path}\n"
                "  AMP style rewards will be disabled. Run scripts/skating/gen_skating_reference.py first."
            )
            self._available = False
            return

        self._available = True
        data = np.load(motion_npz_path)

        # Expected keys in the reference NPZ (generated by gen_skating_reference.py):
        #   amp_obs: (T, amp_obs_dim) float32
        raw = torch.tensor(data["amp_obs"], dtype=torch.float32, device=device)
        T = raw.shape[0]

        if raw.shape[1] != amp_obs_dim:
            print(
                f"[AmpRunner] WARNING: reference motion amp_obs dim={raw.shape[1]} "
                f"!= expected {amp_obs_dim}.  AMP disabled."
            )
            self._available = False
            return

        # Sample buffer_size transitions (with replacement) for quick GPU sampling
        idxs = torch.randint(T, (min(buffer_size, T),))
        self._buffer = raw[idxs]  # (buf_size, amp_obs_dim) on device
        print(f"[AmpRunner] Loaded {self._buffer.shape[0]} expert AMP obs from {motion_npz_path}")

    @property
    def available(self) -> bool:
        return self._available

    def sample(self, n: int) -> torch.Tensor:
        """Sample n random expert AMP observations."""
        idxs = torch.randint(self._buffer.shape[0], (n,), device=self.device)
        return self._buffer[idxs]


class AmpOnPolicyRunner(OnPolicyRunner):
    """OnPolicyRunner extended with an AMP discriminator.

    Extra keys expected in ``train_cfg["amp"]``:

    .. code-block:: python

        amp = dict(
            motion_file          = "path/to/skating_reference.npz",
            amp_obs_dim          = 93,          # determined at runtime if 0
            hidden_dims          = [1024, 512],
            activation           = "leaky_relu",
            learning_rate        = 1e-4,
            replay_buffer_size   = 100_000,
            task_reward_lerp     = 0.5,         # blend: 0=pure task, 1=pure style
            disc_grad_penalty    = 5.0,         # WGAN-GP style gradient penalty
            disc_update_steps    = 3,           # discriminator updates per PPO iter
            disc_mini_batch_size = 4096,
            enabled              = True,        # set False to disable AMP
        )
    """

    # Key in infos["observations"] where the AMP state is stored.
    # The Isaac Lab RslRlVecEnvWrapper places all obs groups under
    # infos["observations"], so "amp" refers to ObservationsCfg.AmpCfg.
    AMP_OBS_KEY = "amp"

    def __init__(self, env: VecEnv, train_cfg: dict, log_dir: str | None = None, device: str = "cpu"):
        super().__init__(env, train_cfg, log_dir=log_dir, device=device)

        self._amp_cfg = train_cfg.get("amp", {})
        self._amp_enabled = self._amp_cfg.get("enabled", True)
        self._task_lerp = float(self._amp_cfg.get("task_reward_lerp", 0.5))
        self._disc_update_steps = int(self._amp_cfg.get("disc_update_steps", 3))
        self._disc_mini_bs = int(self._amp_cfg.get("disc_mini_batch_size", 4096))
        self._grad_pen_coef = float(self._amp_cfg.get("disc_grad_penalty", 5.0))

        if not self._amp_enabled:
            print("[AmpRunner] AMP disabled; running standard PPO.")
            return

        # ── Determine AMP obs dim from first env step ────────────────────────
        obs, extras = self.env.get_observations()
        # AMP obs is in extras["observations"]["amp"] (Isaac Lab convention)
        amp_obs_example = extras.get("observations", {}).get(self.AMP_OBS_KEY, None)
        if amp_obs_example is None:
            print("[AmpRunner] WARNING: no 'amp' obs group in env extras. AMP disabled.")
            self._amp_enabled = False
            return

        amp_obs_dim = self._amp_cfg.get("amp_obs_dim", 0) or amp_obs_example.shape[-1]
        print(f"[AmpRunner] AMP obs dim = {amp_obs_dim}")

        # ── Discriminator ────────────────────────────────────────────────────
        hidden = self._amp_cfg.get("hidden_dims", [1024, 512])
        act = self._amp_cfg.get("activation", "leaky_relu")
        self.discriminator = AmpDiscriminator(amp_obs_dim, hidden, act).to(device)
        self.disc_optimizer = optim.Adam(
            self.discriminator.parameters(),
            lr=float(self._amp_cfg.get("learning_rate", 1e-4)),
        )

        # ── Expert motion buffer ─────────────────────────────────────────────
        motion_file = self._amp_cfg.get("motion_file", "")
        buf_size = int(self._amp_cfg.get("replay_buffer_size", 100_000))
        self.expert_buffer = ExpertMotionBuffer(motion_file, amp_obs_dim, device, buf_size)
        if not self.expert_buffer.available:
            print("[AmpRunner] Expert buffer unavailable — AMP style reward disabled.")
            self._amp_enabled = False
            return

        # ── Policy AMP observation replay buffer (ring buffer) ───────────────
        self._policy_amp_buf = torch.zeros(buf_size, amp_obs_dim, device=device)
        self._policy_buf_ptr = 0
        self._policy_buf_full = False

        print("[AmpRunner] AMP discriminator initialised successfully.")

    # ── Override the learn loop to inject AMP rewards ────────────────────────

    def learn(self, num_learning_iterations: int, init_at_random_ep_len: bool = False):  # noqa: C901
        """Training loop with AMP discriminator reward injection.

        Mirrors parent OnPolicyRunner.learn() exactly, with AMP reward blending
        and discriminator updates injected at the appropriate points.
        """
        if not self._amp_enabled:
            return super().learn(num_learning_iterations, init_at_random_ep_len)

        # ── Writer initialisation (mirrors parent) ────────────────────────────
        if self.log_dir is not None and self.writer is None and not self.disable_logs:
            self.logger_type = self.cfg.get("logger", "tensorboard").lower()
            if self.logger_type == "neptune":
                from rsl_rl.utils.neptune_utils import NeptuneSummaryWriter
                self.writer = NeptuneSummaryWriter(log_dir=self.log_dir, flush_secs=10, cfg=self.cfg)
                self.writer.log_config(self.env.cfg, self.cfg, self.alg_cfg, self.policy_cfg)
            elif self.logger_type == "wandb":
                from rsl_rl.utils.wandb_utils import WandbSummaryWriter
                self.writer = WandbSummaryWriter(log_dir=self.log_dir, flush_secs=10, cfg=self.cfg)
                self.writer.log_config(self.env.cfg, self.cfg, self.alg_cfg, self.policy_cfg)
            else:
                from torch.utils.tensorboard import SummaryWriter
                self.logger_type = "tensorboard"
                self.writer = SummaryWriter(log_dir=self.log_dir, flush_secs=10)

        if init_at_random_ep_len:
            self.env.episode_length_buf = torch.randint_like(
                self.env.episode_length_buf, high=int(self.env.max_episode_length)
            )

        obs, extras = self.env.get_observations()
        privileged_obs = extras["observations"].get(self.privileged_obs_type, obs)
        obs, privileged_obs = obs.to(self.device), privileged_obs.to(self.device)
        self.train_mode()

        ep_infos: list = []
        rewbuffer: deque = deque(maxlen=100)
        lenbuffer: deque = deque(maxlen=100)
        amp_rewbuffer: deque = deque(maxlen=100)
        cur_reward_sum = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)
        cur_amp_sum = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)
        cur_episode_length = torch.zeros(self.env.num_envs, dtype=torch.float, device=self.device)

        start_iter = self.current_learning_iteration
        tot_iter = start_iter + num_learning_iterations

        for it in range(start_iter, tot_iter):
            start = time.time()

            # ── Rollout ───────────────────────────────────────────────────────
            with torch.inference_mode():
                for _ in range(self.num_steps_per_env):
                    actions = self.alg.act(obs, privileged_obs)
                    obs, task_rewards, dones, infos = self.env.step(actions.to(self.env.device))
                    obs, task_rewards, dones = (
                        obs.to(self.device), task_rewards.to(self.device), dones.to(self.device)
                    )

                    # ── AMP reward blending ───────────────────────────────────
                    amp_obs_step = infos.get("observations", {}).get(self.AMP_OBS_KEY, None)
                    if amp_obs_step is not None:
                        amp_obs_step = amp_obs_step.to(self.device)
                        amp_rewards = self.discriminator.get_reward(amp_obs_step)
                        rewards = (1.0 - self._task_lerp) * task_rewards + self._task_lerp * amp_rewards
                        self._store_policy_amp_obs(amp_obs_step)
                    else:
                        rewards = task_rewards
                        amp_rewards = torch.zeros_like(task_rewards)

                    obs = self.obs_normalizer(obs)
                    if self.privileged_obs_type is not None:
                        privileged_obs = self.privileged_obs_normalizer(
                            infos["observations"][self.privileged_obs_type].to(self.device)
                        )
                    else:
                        privileged_obs = obs

                    self.alg.process_env_step(rewards, dones, infos)

                    if self.log_dir is not None:
                        if "episode" in infos:
                            ep_infos.append(infos["episode"])
                        elif "log" in infos:
                            ep_infos.append(infos["log"])
                        cur_reward_sum += rewards
                        cur_amp_sum += amp_rewards
                        cur_episode_length += 1
                        new_ids = (dones > 0).nonzero(as_tuple=False)
                        rewbuffer.extend(cur_reward_sum[new_ids][:, 0].cpu().numpy().tolist())
                        lenbuffer.extend(cur_episode_length[new_ids][:, 0].cpu().numpy().tolist())
                        amp_rewbuffer.extend(cur_amp_sum[new_ids][:, 0].cpu().numpy().tolist())
                        cur_reward_sum[new_ids] = 0
                        cur_amp_sum[new_ids] = 0
                        cur_episode_length[new_ids] = 0

                stop = time.time()
                collection_time = stop - start
                start = stop

                # Compute returns (required before PPO update)
                self.alg.compute_returns(privileged_obs)

            # ── PPO update ────────────────────────────────────────────────────
            loss_dict = self.alg.update()
            torch.cuda.synchronize()

            # ── Discriminator update ──────────────────────────────────────────
            disc_loss = self._update_discriminator()

            stop = time.time()
            learn_time = stop - start
            self.current_learning_iteration = it

            # ── Logging ───────────────────────────────────────────────────────
            if self.log_dir is not None and not self.disable_logs:
                self.log(locals())
                if it % self.save_interval == 0:
                    self.save(os.path.join(self.log_dir, f"model_{it}.pt"))
                # Also log AMP-specific metrics
                if self.writer is not None and len(amp_rewbuffer) > 0:
                    import statistics
                    self.writer.add_scalar("AMP/mean_style_reward", statistics.mean(amp_rewbuffer), it)
                    self.writer.add_scalar("AMP/disc_loss", disc_loss, it)

            ep_infos.clear()

        # ── Final save ────────────────────────────────────────────────────────
        if self.log_dir is not None and not self.disable_logs:
            self.save(os.path.join(self.log_dir, f"model_{self.current_learning_iteration}.pt"))

    # ── Checkpoint helpers ────────────────────────────────────────────────────

    def save(self, path: str, infos=None):
        """Save policy + discriminator state so both can be resumed together."""
        super().save(path, infos)
        # Augment checkpoint with discriminator weights and optimizer
        ckpt = torch.load(path, weights_only=False)
        ckpt["disc_state_dict"] = self.discriminator.state_dict()
        ckpt["disc_optimizer_state_dict"] = self.disc_optimizer.state_dict()
        torch.save(ckpt, path)

    def load(self, path: str, load_optimizer: bool = True):
        """Load policy; also restore discriminator if present in checkpoint."""
        super().load(path, load_optimizer)
        ckpt = torch.load(path, weights_only=False)
        if "disc_state_dict" in ckpt:
            self.discriminator.load_state_dict(ckpt["disc_state_dict"])
            if load_optimizer and "disc_optimizer_state_dict" in ckpt:
                self.disc_optimizer.load_state_dict(ckpt["disc_optimizer_state_dict"])
            print("[AmpRunner] Discriminator state restored from checkpoint.")
        else:
            print("[AmpRunner] No discriminator state in checkpoint — starting fresh.")

    def _store_policy_amp_obs(self, amp_obs: torch.Tensor) -> None:
        """Write a batch of AMP observations into the policy ring buffer."""
        n = amp_obs.shape[0]
        end = self._policy_buf_ptr + n
        buf_size = self._policy_amp_buf.shape[0]
        if end <= buf_size:
            self._policy_amp_buf[self._policy_buf_ptr:end] = amp_obs
        else:
            first = buf_size - self._policy_buf_ptr
            self._policy_amp_buf[self._policy_buf_ptr:] = amp_obs[:first]
            self._policy_amp_buf[:n - first] = amp_obs[first:]
        self._policy_buf_ptr = end % buf_size
        if end >= buf_size:
            self._policy_buf_full = True

    def _sample_policy_amp_obs(self, n: int) -> torch.Tensor | None:
        """Sample n random observations from the policy ring buffer."""
        filled = self._policy_amp_buf.shape[0] if self._policy_buf_full else self._policy_buf_ptr
        if filled < n:
            return None
        idxs = torch.randint(filled, (n,), device=self.device)
        return self._policy_amp_buf[idxs]

    def _update_discriminator(self) -> float:
        """Run several gradient steps on the AMP discriminator."""
        total_loss = 0.0
        for _ in range(self._disc_update_steps):
            expert_batch = self.expert_buffer.sample(self._disc_mini_bs)
            policy_batch = self._sample_policy_amp_obs(self._disc_mini_bs)
            if policy_batch is None:
                break

            policy_batch = policy_batch.detach()

            # Binary cross-entropy: expert → 1, policy → 0
            logits_expert = self.discriminator(expert_batch)
            logits_policy = self.discriminator(policy_batch)

            loss_expert = nn.functional.binary_cross_entropy_with_logits(
                logits_expert, torch.ones_like(logits_expert)
            )
            loss_policy = nn.functional.binary_cross_entropy_with_logits(
                logits_policy, torch.zeros_like(logits_policy)
            )

            loss = loss_expert + loss_policy

            # Gradient penalty disabled: the create_graph=True required for WGAN-GP
            # conflicts with Isaac Sim / PhysX CUDA streams and causes deadlocks.
            # AMP converges reliably with BCE loss alone; GP can be re-enabled once
            # Isaac Sim's CUDA stream synchronisation is better understood.

            self.disc_optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(self.discriminator.parameters(), 1.0)
            self.disc_optimizer.step()
            # Synchronise CUDA streams after each discriminator step to prevent
            # long-running autograd graphs from conflicting with Isaac Sim / PhysX.
            torch.cuda.synchronize()
            total_loss += loss.item()

        return total_loss / max(self._disc_update_steps, 1)

