"""RSL-RL PPO runner configurations for roller-skating.

Two configs are defined:
  - SkatingPhase1PPORunnerCfg : gliding balance, no AMP
  - SkatingEurekaPPORunnerCfg : Eureka-driven full skating (Phase 2+)

AMP is disabled for the Eureka phase because the task-specific reward is
already generated by the LLM; style guidance is left to the reward function
itself (the LLM can use push_off_rhythm / skate_foot_edge_contact helpers).
Enabling AMP is straightforward — set amp["enabled"] = True and point to the
reference motion NPZ if desired.
"""

import os

from isaaclab.utils import configclass
from isaaclab_rl.rsl_rl import RslRlOnPolicyRunnerCfg, RslRlPpoActorCriticCfg, RslRlPpoAlgorithmCfg

_REFERENCE_MOTION_NPZ = os.path.normpath(os.path.join(
    os.path.dirname(__file__),
    "..", "..", "..", "data", "skating_reference.npz",
))

# Human reference motion generated by scripts/skating/retarget_video_to_amp.py
# (YouTube skating video → GENMO SMPL → G1 retargeting → 85-dim AMP obs)
_HUMAN_REFERENCE_NPZ = os.path.normpath(os.path.join(
    os.path.dirname(__file__),
    "..", "..", "..", "data", "skating_reference_human.npz",
))


# ─────────────────────────────────────────────────────────────────────────────
# Phase 1: Gliding balance — pure PPO, no AMP
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class SkatingPhase1PPORunnerCfg(RslRlOnPolicyRunnerCfg):
    """Phase 1: Gliding balance — pure PPO, no AMP (robot just needs to stay upright)."""

    num_steps_per_env = 24
    max_iterations = 2000
    save_interval = 200
    experiment_name = "skating_phase1"
    empirical_normalization = False

    policy = RslRlPpoActorCriticCfg(
        init_noise_std=1.0,
        actor_hidden_dims=[512, 256, 128],
        critic_hidden_dims=[512, 256, 128],
        activation="elu",
    )
    algorithm = RslRlPpoAlgorithmCfg(
        value_loss_coef=1.0,
        use_clipped_value_loss=True,
        clip_param=0.2,
        entropy_coef=0.01,
        num_learning_epochs=5,
        num_mini_batches=4,
        learning_rate=1.0e-3,
        schedule="adaptive",
        gamma=0.99,
        lam=0.95,
        desired_kl=0.01,
        max_grad_norm=1.0,
    )

    amp: dict = {"enabled": False}


# ─────────────────────────────────────────────────────────────────────────────
# Eureka Phase (2+): Full skating — PPO with Eureka-generated task reward
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class SkatingEurekaPPORunnerCfg(RslRlOnPolicyRunnerCfg):
    """Eureka-driven full skating — PPO, no AMP by default.

    This config is used by the Eureka runner for all training subprocesses.
    Each Eureka iteration runs:
        python scripts/skating/train.py \\
            --task Unitree-G1-Skating-Eureka-v0 \\
            --resume --load_experiment skating_phase1 \\
            --experiment_name eureka_iter_N \\
            EUREKA_REWARD_FN_PATH=.../reward_fn.py

    To enable AMP style guidance, set amp["enabled"] = True.
    """

    num_steps_per_env = 24
    max_iterations = 1500     # overridden by --max_iterations from eureka_phase2.py
    save_interval = 300
    experiment_name = "skating_eureka"   # overridden per iteration
    empirical_normalization = False

    policy = RslRlPpoActorCriticCfg(
        init_noise_std=0.8,   # lower than Phase 1 — warm-starting from Phase 1 weights
        actor_hidden_dims=[512, 256, 128],
        critic_hidden_dims=[512, 256, 128],
        activation="elu",
    )
    algorithm = RslRlPpoAlgorithmCfg(
        value_loss_coef=1.0,
        use_clipped_value_loss=True,
        clip_param=0.2,
        entropy_coef=0.008,
        num_learning_epochs=5,
        num_mini_batches=4,
        learning_rate=5.0e-4,
        schedule="adaptive",
        gamma=0.99,
        lam=0.95,
        desired_kl=0.01,
        max_grad_norm=1.0,
    )

    # AMP disabled — LLM reward function handles style guidance.
    # To enable: set enabled=True and provide motion_file path.
    amp: dict = {
        "enabled": False,
        # "enabled": True,
        # "motion_file": _REFERENCE_MOTION_NPZ,
        # "amp_obs_dim": 0,
        # "hidden_dims": [1024, 512],
        # "activation": "leaky_relu",
        # "learning_rate": 1e-4,
        # "replay_buffer_size": 100_000,
        # "task_reward_lerp": 0.3,
        # "disc_grad_penalty": 5.0,
        # "disc_update_steps": 2,
        # "disc_mini_batch_size": 4096,
    }


# ─────────────────────────────────────────────────────────────────────────────
# AMP Phase: Human-video style guidance + fixed task rewards
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class SkatingAMPPPORunnerCfg(RslRlOnPolicyRunnerCfg):
    """AMP-driven skating — PPO + discriminator trained on human reference motion.

    The human reference is generated by the retargeting pipeline::

        python scripts/skating/retarget_video_to_amp.py \\
            --video_url https://www.youtube.com/shorts/4b-bjwTWPRA

    This produces ``data/skating_reference_human.npz`` (T × 85 AMP obs array).

    Training blends two reward signals:
        r_total = (1 - task_reward_lerp) × r_task  +  task_reward_lerp × r_AMP
        r_AMP   = -log(1 - σ(D(s)))   ∈ [0, ~9.2]

    The discriminator D is a small MLP (85 → 1024 → 512 → 1) that distinguishes
    the robot's current AMP obs from the human reference.  As D is fooled, the
    robot naturally develops a human-like skating gait (push-off, arm swing,
    weight transfer) rather than an arbitrary solution.

    Warm-start from Phase 1 (balance/glide) or Phase 4 (high-speed) checkpoint::

        python scripts/skating/train.py \\
            --task Unitree-G1-Skating-AMP-v0 \\
            --num_envs 2048 --headless \\
            --resume_path <checkpoint.pt> \\
            --experiment_name skating_amp \\
            --max_iterations 3000
    """

    num_steps_per_env = 24
    max_iterations = 3000
    save_interval = 300
    experiment_name = "skating_amp"
    empirical_normalization = False

    policy = RslRlPpoActorCriticCfg(
        init_noise_std=0.8,            # warm-starting from Phase 1
        actor_hidden_dims=[512, 256, 128],
        critic_hidden_dims=[512, 256, 128],
        activation="elu",
    )
    algorithm = RslRlPpoAlgorithmCfg(
        value_loss_coef=1.0,
        use_clipped_value_loss=True,
        clip_param=0.2,
        entropy_coef=0.008,
        num_learning_epochs=5,
        num_mini_batches=4,
        learning_rate=5.0e-4,
        schedule="adaptive",
        gamma=0.99,
        lam=0.95,
        desired_kl=0.01,
        max_grad_norm=1.0,
    )

    # AMP enabled — human skating reference from video retargeting pipeline.
    # Run `python scripts/skating/retarget_video_to_amp.py` first to generate
    # the human reference NPZ before training with this config.
    amp: dict = {
        "enabled": True,
        "motion_file": _HUMAN_REFERENCE_NPZ,
        "amp_obs_dim": 85,          # must match mdp/amp_obs.py (29+29+3+3+3+6+6+6)
        "hidden_dims": [1024, 512],
        "activation": "leaky_relu",
        "learning_rate": 1e-5,      # lowered: prevents discriminator from collapsing
        "replay_buffer_size": 100_000,
        # 50% task reward + 50% AMP style reward
        # Increase lerp (→1.0) for pure imitation; decrease (→0.0) for pure task.
        "task_reward_lerp": 0.5,
        "disc_grad_penalty": 0.0,   # disabled: create_graph=True conflicts with PhysX CUDA streams
        "disc_update_steps": 1,     # 1 update per PPO iter keeps disc from getting too far ahead
        "disc_mini_batch_size": 4096,
    }
