"""AMP-driven roller-skating environment for Unitree G1-29DOF.

This environment pairs with the human-motion AMP reference generated by:

    python scripts/skating/retarget_video_to_amp.py \\
        --video_url https://www.youtube.com/shorts/4b-bjwTWPRA

The key differences from Phase 1 (gliding) and Eureka environments:

* Fixed task rewards (no LLM injection, no dynamic EUREKA_REWARD_FN_PATH).
  The AMP discriminator is the primary style signal; task rewards keep the
  robot fast and upright.

* Near-rest reset: robot must push off from near-stationary, exactly like the
  Eureka env. The discriminator reward is highest when the skating motion
  resembles the human reference, directly encouraging push-off gait.

* Curriculum keyed to ``forward_velocity`` reward: advances speed/turning
  commands as the policy improves.

* Same AmpCfg observation group as Phase 1 / Eureka, so the discriminator in
  AmpOnPolicyRunner receives the correct 85-dim state vector.

Architecture:
    r_total = (1 - lerp) × r_task  +  lerp × r_AMP
    r_AMP   = -log(1 - σ(D(s_AMP)))  ∈ [0, ~9]
    lerp    = 0.5  (configured in SkatingAMPPPORunnerCfg)
"""

from isaaclab.envs import ManagerBasedRLEnvCfg
from isaaclab.managers import CurriculumTermCfg as CurrTerm
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import RewardTermCfg as RewTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.utils import configclass

# ── Shared scene / obs / actions / terminations (Phase 1 base)
from .skating_env_cfg import (
    ActionsCfg,
    ObservationsCfg,
    SkatingSceneCfg,
    TerminationsCfg,
)
from unitree_rl_lab.tasks.skating import mdp


# ─────────────────────────────────────────────────────────────────────────────
# Commands — same as Eureka: curriculum-expanded forward + turning
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class AMPCommandsCfg:
    """Skating commands: forward speed + turning, expanded by curriculum.

    Starting range is conservative (0.3–1.5 m/s forward); the curriculum
    advances it to the full 0.3–3.5 m/s range as forward_velocity improves.
    """

    base_velocity = mdp.UniformLevelVelocityCommandCfg(
        asset_name="robot",
        resampling_time_range=(10.0, 10.0),
        rel_standing_envs=0.01,
        rel_heading_envs=1.0,
        heading_command=False,
        debug_vis=True,
        ranges=mdp.UniformLevelVelocityCommandCfg.Ranges(
            lin_vel_x=(0.3, 1.5),
            lin_vel_y=(-0.1, 0.1),
            ang_vel_z=(-0.4, 0.4),
        ),
        limit_ranges=mdp.UniformLevelVelocityCommandCfg.Ranges(
            lin_vel_x=(0.3, 3.5),
            lin_vel_y=(-0.3, 0.3),
            ang_vel_z=(-0.8, 0.8),
        ),
    )


# ─────────────────────────────────────────────────────────────────────────────
# Rewards — fixed task + safety terms only (NO eureka_task / LLM reward).
# AMP discriminator reward is injected by AmpOnPolicyRunner, not here.
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class AMPRewardsCfg:
    """Task and safety rewards for AMP-driven skating.

    The AMP discriminator provides the primary style signal (push-off rhythm,
    weight transfer, arm swing) from the human skating reference.  These rewards
    keep the robot task-directed and physically safe:

      r_total = (1 - lerp) × r_task  +  lerp × r_AMP
                     ↑ these rewards          ↑ from discriminator

    Term weights were tuned so that:
      - Survival / posture act as soft constraints (robot does not fall)
      - forward_velocity is the main task gradient
      - Energy / smoothness discourage thrashing
    """

    # ── Survival ─────────────────────────────────────────────────────────────
    alive = RewTerm(func=mdp.is_alive, weight=0.5)

    # ── Speed tracking (primary task reward) ─────────────────────────────────
    # Exponential kernel: reward = exp(-|v_x - v_cmd|^2 / std^2)
    # The AMP discriminator will shape *how* the robot achieves this speed.
    forward_velocity = RewTerm(
        func=mdp.forward_velocity_tracking_exp,
        weight=3.0,
        params={"command_name": "base_velocity", "std": 0.5},
    )

    # ── Angular velocity damping ──────────────────────────────────────────────
    # Penalise uncontrolled spinning; the AMP style reward handles gait quality.
    ang_vel_z = RewTerm(func=mdp.ang_vel_z_l2, weight=-0.05)

    # ── Posture / balance ─────────────────────────────────────────────────────
    upright = RewTerm(func=mdp.upright_orientation_l2, weight=-5.0)
    base_height = RewTerm(
        func=mdp.base_height_skating_l2,
        weight=-10.0,
        params={"target_height": 0.85},
    )
    lateral_vel = RewTerm(func=mdp.lateral_velocity_penalty, weight=-1.0)

    # ── Efficiency / smoothness ───────────────────────────────────────────────
    energy      = RewTerm(func=mdp.skate_energy,      weight=-2e-5)
    action_rate = RewTerm(func=mdp.skate_action_rate, weight=-0.05)
    joint_acc   = RewTerm(func=mdp.joint_acc_l2,      weight=-2.5e-7)
    dof_pos_limits = RewTerm(func=mdp.joint_pos_limits, weight=-5.0)

    # ── Posture naturalness ───────────────────────────────────────────────────
    joint_deviation_arms = RewTerm(
        func=mdp.joint_deviation_l1,
        weight=-0.1,
        params={
            "asset_cfg": SceneEntityCfg(
                "robot",
                joint_names=[".*_shoulder_.*_joint", ".*_elbow_joint", ".*_wrist_.*"],
            )
        },
    )
    joint_deviation_waist = RewTerm(
        func=mdp.joint_deviation_l1,
        weight=-0.5,
        params={"asset_cfg": SceneEntityCfg("robot", joint_names=["waist.*"])},
    )

    # ── Contact safety ────────────────────────────────────────────────────────
    undesired_contacts = RewTerm(
        func=mdp.undesired_contacts,
        weight=-1.0,
        params={
            "threshold": 1.0,
            "sensor_cfg": SceneEntityCfg(
                "contact_forces",
                body_names=["(?!.*ankle.*).*"],
            ),
        },
    )


# ─────────────────────────────────────────────────────────────────────────────
# Events — same near-rest reset as Eureka (robot must push off)
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class AMPEventCfg:
    """Domain randomisation for the AMP phase.

    Episodes start from near-rest so the robot must push off to earn both
    the task reward (forward velocity) and the AMP style reward (gait matches
    the human reference).
    """

    attach_skates = EventTerm(
        func=mdp.attach_skates_to_robot,
        mode="startup",
    )

    skate_friction = EventTerm(
        func=mdp.randomize_rigid_body_material,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names=".*ankle_roll.*"),
            "static_friction_range":  (0.01, 0.03),
            "dynamic_friction_range": (0.005, 0.02),
            "restitution_range": (0.0, 0.0),
            "num_buckets": 16,
        },
    )

    add_base_mass = EventTerm(
        func=mdp.randomize_rigid_body_mass,
        mode="startup",
        params={
            "asset_cfg": SceneEntityCfg("robot", body_names="torso_link"),
            "mass_distribution_params": (-1.0, 2.0),
            "operation": "add",
        },
    )

    # Near-rest reset: robot must push off — AMP discriminator rewards
    # motions that look like the human reference (which includes push-off)
    reset_base = EventTerm(
        func=mdp.reset_skating_pose,
        mode="reset",
        params={
            "pose_range": {"x": (-1.5, 1.5), "y": (-1.5, 1.5), "yaw": (-3.14, 3.14)},
            "init_velocity_range": {"x": (0.0, 0.5)},
        },
    )

    reset_robot_joints = EventTerm(
        func=mdp.reset_joints_by_scale,
        mode="reset",
        params={"position_range": (1.0, 1.0), "velocity_range": (0.0, 0.0)},
    )

    push_robot = EventTerm(
        func=mdp.push_by_setting_velocity,
        mode="interval",
        interval_range_s=(6.0, 10.0),
        params={"velocity_range": {"x": (-0.5, 0.5), "y": (-0.3, 0.3)}},
    )


# ─────────────────────────────────────────────────────────────────────────────
# Curriculum — keyed to forward_velocity reward (task reward term)
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class AMPCurriculumCfg:
    """Advance speed/turning commands when forward_velocity reward improves.

    Uses the same ``skating_lin_vel_cmd_levels`` and ``skating_ang_vel_cmd_levels``
    curriculum functions as the Eureka env, but keyed to ``forward_velocity``
    (the fixed task reward) rather than the dynamic ``eureka_task`` reward.
    """

    lin_vel_cmd_levels = CurrTerm(
        mdp.skating_lin_vel_cmd_levels,
        params={"reward_term_name": "forward_velocity"},
    )
    ang_vel_cmd_levels = CurrTerm(
        mdp.skating_ang_vel_cmd_levels,
        params={"reward_term_name": "forward_velocity"},
    )


# ─────────────────────────────────────────────────────────────────────────────
# Environment
# ─────────────────────────────────────────────────────────────────────────────

@configclass
class G1SkatingAMPEnvCfg(ManagerBasedRLEnvCfg):
    """AMP-driven full skating environment.

    Task rewards are fixed (forward velocity + safety).
    Style/gait rewards come from the AMP discriminator trained on human video.

    The AmpCfg observation group (85-dim) is inherited from ObservationsCfg;
    AmpOnPolicyRunner reads it from infos["observations"]["amp"] at each step
    and feeds it to the discriminator.

    To train::

        python scripts/skating/train.py \\
            --task Unitree-G1-Skating-AMP-v0 \\
            --num_envs 2048 --headless \\
            --resume_path <phase1_checkpoint> \\
            --experiment_name skating_amp \\
            --max_iterations 3000
    """

    scene: SkatingSceneCfg = SkatingSceneCfg(num_envs=2048, env_spacing=4.0)
    observations: ObservationsCfg = ObservationsCfg()
    actions: ActionsCfg = ActionsCfg()
    commands: AMPCommandsCfg = AMPCommandsCfg()
    rewards: AMPRewardsCfg = AMPRewardsCfg()
    terminations: TerminationsCfg = TerminationsCfg()
    events: AMPEventCfg = AMPEventCfg()
    curriculum: AMPCurriculumCfg = AMPCurriculumCfg()

    def __post_init__(self):
        self.decimation = 4            # 50 Hz policy (sim dt=0.005 s)
        self.episode_length_s = 20.0
        self.sim.dt = 0.005
        self.sim.render_interval = self.decimation
        self.sim.physics_material = self.scene.terrain.physics_material
        self.sim.physx.gpu_max_rigid_patch_count = 10 * 2**15
        self.scene.contact_forces.update_period = self.sim.dt


@configclass
class G1SkatingAMPPlayEnvCfg(G1SkatingAMPEnvCfg):
    """Play/eval variant: fewer envs, full command range."""

    def __post_init__(self):
        super().__post_init__()
        self.scene.num_envs = 32
        self.commands.base_velocity.ranges = self.commands.base_velocity.limit_ranges
